#include "locale_descriptor.hpp"
#include <QRegularExpression>
#include <exception>

Tts::LocaleDescriptor::LocaleDescriptor()
    : language(QLocale::C), territory(QLocale::AnyTerritory)
{
}

Tts::LocaleDescriptor::LocaleDescriptor(const QLocale::Language &l,
                                        const QLocale::Territory &t)
    : language(l), territory(t)
{
}

Tts::LocaleDescriptor::LocaleDescriptor(const QLocale &l)
    : language(l.language()), territory(l.territory())
{
}

auto Tts::LocaleDescriptor::fromFileName(const QString &qmFileName)
    -> LocaleDescriptor
{
    // Regex for parsing the locale name from a translation resource file
    // name.
    // File names as generated by ldebug und lrelease are assumed to have
    // the form [prefix]xx.qm or [prefix]xx_XX.qm, with the prefix set
    // in qt_add_translations.
    // A third letter for language or territory is also possible, and the
    // delimiter could also be '-'.
    // The file name is assumed to not contain a script code.
    static const auto qmLocaleNameRegex =
        QRegularExpression("^.*([a-z]{2,3})([_-][A-Z]{2,3}){,1}.qm$");

    QRegularExpressionMatch match = qmLocaleNameRegex.match(qmFileName);
    if (!match.hasMatch())
        throw std::invalid_argument(
            "Invalid file name format. The expected format is xx.qm or"
            "xx_XX.qm/xx-XX.qm with a third x/X also being valid.");

    QLocale::Language language = QLocale::codeToLanguage(match.captured(1));
    QLocale::Territory territory = QLocale::AnyTerritory;
    if (match.lastCapturedIndex() >= 2) {
        // (This group starts with the delimiter; remove the first char.)
        territory = QLocale::codeToTerritory(match.captured(2).removeAt(0));
    }

    return Tts::LocaleDescriptor(language, territory);
}

auto Tts::LocaleDescriptor::fromResourcePath(const QString &qmPath)
    -> LocaleDescriptor
{
    if (qmPath.isEmpty() || qmPath.endsWith("/"))
        return Tts::LocaleDescriptor();

    // TODO if I don't use QFile for parsing, should I handle other
    // separators than "/"?
    QString fileName = *(--qmPath.split("/").end());
    return fromFileName(fileName);
}

bool Tts::LocaleDescriptor::operator==(const Tts::LocaleDescriptor &ld) const
{
    return language == ld.language && territory == ld.territory;
}

bool Tts::LocaleDescriptor::operator<(const Tts::LocaleDescriptor &ld) const
{
    return language < ld.language
        || (language == ld.language && territory < ld.territory);
}

std::ostream &Tts::operator<<(std::ostream &os, const Tts::LocaleDescriptor &ld)
{
    auto languageStr = QLocale::languageToString(ld.language);
    auto territoryStr = QLocale::territoryToString(ld.territory);

    return os << "(" << languageStr.toUtf8().data() << ", "
              << territoryStr.toUtf8().data() << ")";
}
