#include "locale_descriptor.hpp"
#include <regex>
#include <stdexcept>
#include <filesystem>

Tts::LocaleDescriptor::LocaleDescriptor()
    : language(Language::c), territory(Territory::ANY)
{
}

Tts::LocaleDescriptor::LocaleDescriptor(const Language::Code &l,
                                        const Territory::Code &t)
    : language(l), territory(t)
{
}

Tts::LocaleDescriptor::LocaleDescriptor(const Locale &l)
    : language(l.language()), territory(l.territory())
{
}

auto Tts::LocaleDescriptor::fromFileName(const std::string &fileName)
    -> LocaleDescriptor
{
    // Regex for parsing the locale name from a translation resource file
    // name.
    // File names as generated by ldebug und lrelease are assumed to have
    // the form [prefix]xx.qm or [prefix]xx_XX.qm, with the prefix set
    // in qt_add_translations.
    // A third letter for language or territory is also possible, and the
    // delimiter could also be '-'.
    // The file name is assumed to not contain a script code.
    static const std::regex localeNameRegex(
        "([a-z]{2,3})([_-][A-Z]{2,3})?\\." TRANSLATION_FILE_ENDING "$");

    std::smatch match;
    if (!std::regex_search(fileName, match, localeNameRegex))
        throw std::invalid_argument(
            "Invalid file name format " + fileName
            + ". The expected format is xx." TRANSLATION_FILE_ENDING " or "
              "xx_XX." TRANSLATION_FILE_ENDING "/xx-XX." TRANSLATION_FILE_ENDING
              " with a third x/X also being valid.");

    Language::Code language = Language::c;
    Territory::Code territory = Territory::ANY;

    // The first match contains the complete sequence; groups can be at
    // indices >= 1.
    if (match.size() > 1)
        language = Language::fromString(match[1]);
    if (match.size() > 2) {
        // There could be an empty match for the second group.
        auto t = match[2].str();
        if (t.length() > 0) {
            // This group starts with the delimiter; remove the first character.
            t.erase(t.begin());
            territory = Territory::fromString(t);
        }
    }

    return Tts::LocaleDescriptor(language, territory);
}

auto Tts::LocaleDescriptor::fromResourcePath(const std::string &path)
    -> LocaleDescriptor
{
    if (path.empty() || path.ends_with("/") /* C++20 */)
        return LocaleDescriptor();

    std::string filename = std::filesystem::path(path).filename().string();
    return fromFileName(filename);
}

bool Tts::LocaleDescriptor::operator==(const LocaleDescriptor &ld) const
{
    return language == ld.language && territory == ld.territory;
}

bool Tts::LocaleDescriptor::operator<(const LocaleDescriptor &ld) const
{
    return language < ld.language
        || (language == ld.language && territory < ld.territory);
}

std::ostream &Tts::operator<<(std::ostream &os, const LocaleDescriptor &ld)
{
    return os << "(" << Language::toString(ld.language) << ", "
              << Territory::toString(ld.territory) << ")";
}
