#include "translator_resources.hpp"
#include <QFile>
#include <QDirIterator>

auto Tts::Translator::resources() -> ResourceMap
{
    static ResourceMap resources;

    if (resources.size() > 0)
        return resources;

    // ":" is the base path for Qt Resource files.
    QDirIterator it(":", { "*.qm" }, QDir::Files, QDirIterator::Subdirectories);
    while (it.hasNext()) {
        QString dir = it.next();
        auto file = QFile(dir);
        // TODO maybe split the directory string instead of parsing over QFile?

        // Regex for parsing the locale name from a translation resource file
        // name.
        // File names as generated by ldebug und lrelease are assumed to have
        // the form [prefix]xx.qm or [prefix]xx_XX.qm, with the prefix set
        // in qt_add_translations.
        // A third letter for language or territory is also possible, and the
        // delimiter could also be '-'.
        // The file name is assumed to not contain a script code.
        static const auto qmLocaleNameRegex =
            QRegularExpression("^.*([a-z]{2,3})([_-][A-Z]{2,3}){,1}.qm$");

        auto l = QLocale(file.fileName().replace(qmLocaleNameRegex, "\\1\\2"));

        resources.insert(LocaleDescriptor(l), dir);
    }

    return resources;
}
